openapi: 3.0.0
servers:
  - url: 'http://api.raonix.com/nemoahnApi/1.0.0'
info:
  description: This is NemoAhn API.
  version: 1.0.0
  title: NemoAhn
  contact:
    name: NemoAhn Hub API
    url: 'http://www.raonix.com'
    email: raonix@raonix.co.kr
paths:
  '/hubs/{hubId}':
    put:
      tags:
        - hub
      parameters:
        - $ref: '#/components/parameters/deviceIdParam'
        - in: query
          name: upgrade
          schema:
            type: boolean
        - in: query
          name: reboot
          schema:
            type: boolean
      responses:
        '200':
          description: successful operation
  '/hubs/{hubId}/software':
    put:
      tags:
        - hub
      summary: upgrade software
      parameters:
        - $ref: '#/components/parameters/deviceIdParam'
      responses:
        '200':
          description: successful operation
  '/hubs/{hubId}/devices':
    get:
      tags:
        - hub
      summary: Device list
      parameters:
        - $ref: '#/components/parameters/deviceIdParam'
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/DeviceModel'
        '400':
          description: Invalid Device Id supplied
        '404':
          description: Not found
  '/hubs/{hubId}/devices/state':
    get:
      tags:
        - hub
      summary: Devices state list
      parameters:
        - $ref: '#/components/parameters/deviceIdParam'
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DeviceStateModel'
        '400':
          description: Invalid Device Id supplied
        '404':
          description: Not found
components:
  parameters:
    deviceIdParam:
      name: hubId
      in: path
      required: true
      description: NemoAhn Hub's ID
      schema:
        type: string
  schemas:
    DeviceModel:
      type: object
      properties:
        devices:
          type: array
          items:
            type: object
            properties:
              deviceType:
                type: string
              deviceId:
                type: string
              deviceInfo:
                type: object
                properties:
                  manufacturer:
                    type: string
                  model:
                    type: string
                  hwVersion:
                    type: string
                  swVersion:
                    type: string
              attributes:
                oneOf:
                  - $ref: 'http://www.raonix.com/thermostat.yaml#/components/schemas/AttributeModel'
                  - $ref: 'http://www.raonix.com/light.yaml#/components/schemas/AttributeModel'
              name:
                type: object
                properties:
                  defaultName:
                    type: string
                  nickname:
                    type: string
    DeviceStateModel:
      type: object
      properties:
        devices:
          type: array
          items:
            type: object
            properties:
              deviceType:
                type: string
              deviceId:
                type: string
              nickname:
                type: string
              online:
                type: boolean
